"""
Report Entity

Represents an intelligence report generated by the system.
Reports aggregate signals, analysis, and strategic insights.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, Set, List, Dict, Any
from enum import Enum

from ..value_objects.entity_id import EntityId
from ..value_objects.confidence import Confidence
from ..value_objects.timestamp import Timestamp


class ReportFormat(Enum):
    """Output format for reports."""
    MARKDOWN = "markdown"
    JSON = "json"
    PDF = "pdf"
    HTML = "html"


class ReportStatus(Enum):
    """Status of report generation."""
    DRAFT = "draft"
    GENERATING = "generating"
    COMPLETED = "completed"
    FAILED = "failed"


class ReportType(Enum):
    """Type of intelligence report."""
    DAILY_BRIEF = "daily_brief"
    WEEKLY_SUMMARY = "weekly_summary"
    MONTHLY_DEEP_DIVE = "monthly_deep_dive"
    COMPANY_PROFILE = "company_profile"
    COMPETITIVE_LANDSCAPE = "competitive_landscape"
    MARKET_ANALYSIS = "market_analysis"
    SIGNAL_DIGEST = "signal_digest"
    STRATEGIC_FORECAST = "strategic_forecast"
    CUSTOM = "custom"


@dataclass(frozen=True)
class ReportSection:
    """
    A section within a report.

    Sections organize report content into logical parts.
    """

    id: str
    title: str
    content: str
    order: int
    subsections: List["ReportSection"] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def word_count(self) -> int:
        """Count words in the section content."""
        return len(self.content.split())


@dataclass(frozen=True)
class Report:
    """
    Report entity representing an intelligence report.

    Reports aggregate signals, analysis, and strategic insights
    into human-readable formats.

    Attributes:
        id: Unique identifier for the report
        title: Report title
        report_type: Type/category of report
        status: Generation status
        format: Output format
        summary: Brief summary of the report
        content: Full report content (for JSON/Markdown)
        sections: Structured sections of the report
        company_ids: Companies covered in this report
        signal_ids: Signals included in this report
        tags: Tags for categorization and filtering
        confidence: Overall confidence level of the report
        requested_by: User or system that requested this report
        generated_by: Agent or system that generated this report
        requested_at: When the report was requested
        generated_at: When the report was generated
        created_at: When this report entity was created
        updated_at: When this report was last updated
        metadata: Additional report-specific data
        file_path: Path to generated file (for PDF/HTML)
    """

    id: EntityId
    title: str
    report_type: ReportType
    status: ReportStatus = ReportStatus.DRAFT
    format: ReportFormat = ReportFormat.MARKDOWN
    summary: Optional[str] = None
    content: Optional[str] = None
    sections: List[ReportSection] = field(default_factory=list)
    company_ids: Set[EntityId] = field(default_factory=set)
    signal_ids: Set[EntityId] = field(default_factory=set)
    tags: Set[str] = field(default_factory=set)
    confidence: Confidence = field(default_factory=lambda: Confidence.medium())
    requested_by: Optional[str] = None
    generated_by: Optional[str] = None
    requested_at: Optional[Timestamp] = None
    generated_at: Optional[Timestamp] = None
    created_at: Timestamp = field(default_factory=lambda: Timestamp.now())
    updated_at: Timestamp = field(default_factory=lambda: Timestamp.now())
    metadata: Dict[str, Any] = field(default_factory=dict)
    file_path: Optional[str] = None

    def __post_init__(self) -> None:
        """Validate the report entity."""
        if not self.title or not self.title.strip():
            raise ValueError("Report title cannot be empty")

    @property
    def is_complete(self) -> bool:
        """Check if report generation is complete."""
        return self.status == ReportStatus.COMPLETED

    @property
    def is_failed(self) -> bool:
        """Check if report generation failed."""
        return self.status == ReportStatus.FAILED

    @property
    def signal_count(self) -> int:
        """Number of signals in the report."""
        return len(self.signal_ids)

    @property
    def company_count(self) -> int:
        """Number of companies covered."""
        return len(self.company_ids)

    @property
    def word_count(self) -> int:
        """Total word count of the report."""
        if self.content:
            return len(self.content.split())
        return sum(section.word_count for section in self.sections)

    @property
    def section_count(self) -> int:
        """Number of sections in the report."""
        return len(self.sections)

    @property
    def generation_time_seconds(self) -> Optional[int]:
        """Time taken to generate the report in seconds."""
        if self.requested_at and self.generated_at:
            delta = self.generated_at - self.requested_at
            return int(delta.total_seconds())
        return None

    def add_company(self, company_id: EntityId) -> "Report":
        """Add a company to the report."""
        return Report(
            id=self.id,
            title=self.title,
            report_type=self.report_type,
            status=self.status,
            format=self.format,
            summary=self.summary,
            content=self.content,
            sections=self.sections,
            company_ids=self.company_ids | {company_id},
            signal_ids=self.signal_ids,
            tags=self.tags,
            confidence=self.confidence,
            requested_by=self.requested_by,
            generated_by=self.generated_by,
            requested_at=self.requested_at,
            generated_at=self.generated_at,
            created_at=self.created_at,
            updated_at=Timestamp.now(),
            metadata=self.metadata,
            file_path=self.file_path,
        )

    def add_signal(self, signal_id: EntityId) -> "Report":
        """Add a signal to the report."""
        return Report(
            id=self.id,
            title=self.title,
            report_type=self.report_type,
            status=self.status,
            format=self.format,
            summary=self.summary,
            content=self.content,
            sections=self.sections,
            company_ids=self.company_ids,
            signal_ids=self.signal_ids | {signal_id},
            tags=self.tags,
            confidence=self.confidence,
            requested_by=self.requested_by,
            generated_by=self.generated_by,
            requested_at=self.requested_at,
            generated_at=self.generated_at,
            created_at=self.created_at,
            updated_at=Timestamp.now(),
            metadata=self.metadata,
            file_path=self.file_path,
        )

    def with_content(self, content: str) -> "Report":
        """Update report content."""
        return Report(
            id=self.id,
            title=self.title,
            report_type=self.report_type,
            status=self.status,
            format=self.format,
            summary=self.summary,
            content=content,
            sections=self.sections,
            company_ids=self.company_ids,
            signal_ids=self.signal_ids,
            tags=self.tags,
            confidence=self.confidence,
            requested_by=self.requested_by,
            generated_by=self.generated_by,
            requested_at=self.requested_at,
            generated_at=self.generated_at,
            created_at=self.created_at,
            updated_at=Timestamp.now(),
            metadata=self.metadata,
            file_path=self.file_path,
        )

    def with_status(self, status: ReportStatus) -> "Report":
        """Update report status."""
        generated_at = self.generated_at
        if status == ReportStatus.COMPLETED and self.generated_at is None:
            generated_at = Timestamp.now()

        return Report(
            id=self.id,
            title=self.title,
            report_type=self.report_type,
            status=status,
            format=self.format,
            summary=self.summary,
            content=self.content,
            sections=self.sections,
            company_ids=self.company_ids,
            signal_ids=self.signal_ids,
            tags=self.tags,
            confidence=self.confidence,
            requested_by=self.requested_by,
            generated_by=self.generated_by,
            requested_at=self.requested_at,
            generated_at=generated_at,
            created_at=self.created_at,
            updated_at=Timestamp.now(),
            metadata=self.metadata,
            file_path=self.file_path,
        )

    def with_file_path(self, file_path: str) -> "Report":
        """Set the file path for generated report."""
        return Report(
            id=self.id,
            title=self.title,
            report_type=self.report_type,
            status=ReportStatus.COMPLETED,
            format=self.format,
            summary=self.summary,
            content=self.content,
            sections=self.sections,
            company_ids=self.company_ids,
            signal_ids=self.signal_ids,
            tags=self.tags,
            confidence=self.confidence,
            requested_by=self.requested_by,
            generated_by=self.generated_by,
            requested_at=self.requested_at,
            generated_at=self.generated_at or Timestamp.now(),
            created_at=self.created_at,
            updated_at=Timestamp.now(),
            metadata=self.metadata,
            file_path=file_path,
        )

    def add_tag(self, tag: str) -> "Report":
        """Add a tag to the report."""
        return Report(
            id=self.id,
            title=self.title,
            report_type=self.report_type,
            status=self.status,
            format=self.format,
            summary=self.summary,
            content=self.content,
            sections=self.sections,
            company_ids=self.company_ids,
            signal_ids=self.signal_ids,
            tags=self.tags | {tag.lower().strip()},
            confidence=self.confidence,
            requested_by=self.requested_by,
            generated_by=self.generated_by,
            requested_at=self.requested_at,
            generated_at=self.generated_at,
            created_at=self.created_at,
            updated_at=Timestamp.now(),
            metadata=self.metadata,
            file_path=self.file_path,
        )

    @classmethod
    def create(
        cls,
        title: str,
        report_type: ReportType,
        requested_by: Optional[str] = None,
    ) -> "Report":
        """Factory method to create a new Report."""
        requested_at = Timestamp.now() if requested_by else None
        return cls(
            id=EntityId.generate(),
            title=title,
            report_type=report_type,
            requested_by=requested_by,
            requested_at=requested_at,
        )


__all__ = [
    "Report",
    "ReportFormat",
    "ReportStatus",
    "ReportType",
    "ReportSection",
]